repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    version: 25.27.0
    values:
      - ./values.yaml