nameOverride: "helm-registry"
appVersion: 1.0.0
environment: dev
k8s:
  defaultNode: minikube
  namespace: helm-registry
  deployment:
    kind: Deployment
    enabled: true
    image:
      registry: ghcr.io
      tag: helm/chartmuseum:v0.14.0
      pullPolicy: Always
    replicaCount: 1
    resources:
      limits:
        memory: 1024Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 100m
    enableProbes: true 
    startupProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
      successThreshold: 1
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
      successThreshold: 1
      httpGet:
        path: /
        port: 8080
    livenessProbe:
      initialDelaySeconds: 40
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1
      httpGet:
        path: /
        port: 8080
    environment:
      extraVars: 
      - name: STORAGE
        value: local
      - name: STORAGE_LOCAL_ROOTDIR
        value: /charts
      - name: DEBUG
  persistentVolume:
    enabled: true
    accessModes: ReadWriteMany
    annotations: {}
    claim: helm-registry
    mountPath: /charts
    size: 15Gi
    class: local-storage
    subPath: ""
    localPath: /volumes/helm
    persistentVolumeReclaimPolicy: Retain
    name: helm-registry
  service:
    enabled: true
    name: http
    type: LoadBalancer
    externalPort: 8080
    internalPort: 8080
    protocol: TCP
  ingress:
    enabled: true
    ingressClassName: nginx
    rules:
    - host: helm-registry.localhost
      paths:
      - path: /
        pathType: Prefix