# Default values

# Override the chart name
# nameOverride: ""

# The service this workload is part of
# fullappOverride: ""

# Environment:
environment: dev

k8s:
  # extraAnnotations: {}
  # If Namespace is not set, wil use chart name
  # namespace: ""
  deployment:
    # Either Deployment or StatefulSet
    kind: Deployment
      # In case of StatefulSet, set podManagementPolicy
      # podManagementPolicy: ""
    # Enabled by default
    enabled: true
    # Image to use
    image:
      # Registry to pull from
      # registry: localhost:5000
      # Tag to use
      tag: latest
      # ImagePullPolicy
      pullPolicy: IfNotPresent
    # Default command and args are empty
    # command:
    # args:
    replicaCount: 1
    # Requests and limits:
    resources:
      requests:
        cpu: 10m
        memory: 35Mi
      # limits:
      #   cpu:
      #   memory:
    # Decide if we want probes or not, mostly for testing or debugging purposes
    enableProbes: true 
    startupProbe:
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
      successThreshold: 1
      httpGet:
        path: /health
        port: 8080
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
      successThreshold: 1
      httpGet:
        path: /health
        port: 8080
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1
      httpGet:
        path: /health
        port: 8080
    # Deployment strategy configuration
    strategy:
      type: RollingUpdate
      maxSurge: "25%"
      maxUnavailable: "25%"
    # In case you need to set hosts
    hostAliases: []
    # Node tolerations
    tolerations: []
    # Node selector
    nodeSelector:
    # Node affinity
    nodeAffinity:
    # pod annotiations
    # extraPodAnnotations:
    environment:
      # Environment variables
      extraVars: []
      # Example:
      # extraVars: []
      # - name: varName
      #   value: "varValue"
      # Ports, by default we open service 
      extraPorts: []
        # - name : portName
        #   protocol: TCP
        #   port: 8080
    serviceAccount:
      # Wether or not to create a service account
      create: false
      # If create is true and no name is provided, template 'base.name' will be used
      name: ""
      # Annotations for the service account
      annotations: {}
    # Security Context, only used if set
    securityContext:
  hpa:
    # Enabled by default
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 90
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max # Min, Max or Disabled
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max # Min, Max or Disabled
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
  persistentVolume:
    # Disabled by default
    enabled: false
    accessModes: ReadWriteMany
    annotations: {}
    claim:
    mountPath: /data
    size: 2Gi
    # class:
    subPath: ""
    # localPath: # I use /d/images/registry/registry for the registry, as i have my registry mounted on minikube from a local folder
    persistentVolumeReclaimPolicy: Retain
  service:
    # Enabled by default
    enabled: true
    name: http
    type: ClusterIP # ClusterIP, LoadBalancer or NodePort
    # If LoadBalancerIP is not set and you are using LoadBalancer, it will be an ephemeral IP address
    # loadBalancerIP: X.X.X.X
    externalPort: 80
    internalPort: 8080
    protocol: TCP # TCP, UDP or SCTP if your K8s allows it
    extraPorts: []
  monitoring:
    serviceMonitor:
      # Disabled by default
      enabled: false
      endpoints: []
  ingress:
    # Disabled by default
    enabled: false
    ingressClassName: nginx
    # tls:
    # - hosts: []
    #   secretName: 
    rules:
    - host:
      paths:
      - path:
        pathType: