releases:
  - name: arc
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    namespace: arc
    version: 0.9.3
    values:
      - ./controller.values.yaml
  - name: arc-runner-set
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    namespace: arc
    version: 0.9.3
    values:
      - ./scaleset.values.yaml