repositories:
  - name: helm-repository 
    url: http://helm-registry.helm-registry.svc.cluster.local:8080/
releases:
  - name: docker-registry
    namespace: registries
    chart: helm-repository/base
    version: v1.0.1
    values:
      - ./values.yaml