{{- if .Values.k8s.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "base.name" . }}
  labels:
    {{ include "base.labels" . | nindent 4 }}
  annotations:
    {{ .Values.k8s.extraAnnotations }}
  namespace: {{ if .Values.k8s.namespace }}{{ .Values.k8s.namespace }}{{ else }}{{ template "base.name" . }}{{- end }}
spec:
  accessModes:
    - {{ .Values.k8s.persistentVolume.accessModes }}
  {{- if .Values.k8s.persistentVolume.class }}
  storageClassName: {{ .Values.k8s.persistentVolume.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.k8s.persistentVolume.size | quote }}
{{- end }}