{{- if .Values.k8s.deployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base.name" . }}
  labels:
    {{ include "base.labels" . | nindent 4 }}
  annotations:
    {{ .Values.k8s.extraAnnotations }}
    {{- if .Values.k8s.deployment.serviceAccount.annotations }}
    {{ toYaml .Values.k8s.delpoyment.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  namespace: {{ if .Values.k8s.namespace }}{{ .Values.k8s.namespace }}{{ else }}{{ template "base.name" . }}{{- end }}
{{- end }}