name: Base chart

on:
  push:
    tags:
      - 'chart-base/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # We only have a build job
  build:
    # We run on our arc runners
    runs-on: arc-runner-set
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Split tag name
        env:
          TAG: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=version::${TAG##*/}"
      - name: Check if chart renders
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cd charts/base
          helm template .
      - name: Package and push helm chart
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cd charts/base
          helm package . --version ${{ steps.split.outputs.version }}
          curl --data-binary "@base-${{ steps.split.outputs.version }}.tgz" http://helm-registry.helm-registry.svc.cluster.local:8080/api/charts