name: Prometheus

env:
  version: v1.0.0

# Triggers the workflow on push events only when affecting either the workflow or the prometheus folder
on:
  push:
    tags-ignore:
      - 'image-**'
      - 'chart-**'
    branches:
      - '**'
    paths:
      - '.github/workflows/prometheus.yml'
      - 'tools/monitoring/prometheus/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # We only have a deploy job
  deploy:
    # We run on our arc runners
    runs-on: arc-runner-set
    steps:
      ### We should have a step that chooses a context based on the environment changed, but as we only have one environment it does not matter
      # Checks-out repository under $GITHUB_WORKSPACE and inits and applies helmfile, installing a prometheus helm chart
      - uses: actions/checkout@v4
      - name: Init and apply the helmfile
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cd tools/monitoring/prometheus
          yes | helmfile init
          yes | helmfile apply